import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_constants.dart';
import '../../core/network/api_exception.dart';
import '../../models/order.dart';
import '../../providers/auth_provider.dart';
import '../../providers/order_provider.dart';
import '../main_shell.dart';
import '../order_confirmation/order_confirmation_screen.dart';

/// IMPORTANT - read before trusting this screen with real money:
///
/// This is the one part of the whole app I could not verify by reading
/// the actual backend source, because there IS no backend source for a
/// third-party SDK - razorpay_flutter's exact behavior can only be
/// confirmed by actually running it against a real Razorpay test-mode
/// account on a real device. Everything here matches razorpay_flutter's
/// well-established, long-stable API shape as I understand it, and the
/// field names sent to /payments/verify are confirmed against the real
/// PaymentController (see OrderService.verifyPayment) - but the SDK
/// integration itself - the exact keys 'order_id' vs 'razorpay_order_id'
/// the options map expects, whether 'external_wallet' fires in ways that
/// need separate handling, platform-specific setup in
/// android/ios (this app has no android/ios folders yet - they get
/// generated by `flutter create`, and Razorpay needs some native
/// configuration beyond that, e.g. AndroidManifest proguard rules for
/// release builds) - none of that has been exercised. Test this
/// specifically, with Razorpay test-mode keys, before it goes anywhere
/// near a real transaction.
class PaymentScreen extends StatefulWidget {
  const PaymentScreen({super.key, required this.order});

  final Order order;

  @override
  State<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends State<PaymentScreen> {
  late final Razorpay _razorpay;
  bool _isProcessing = true;
  String? _gatewayOrderId;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _onPaymentSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _onPaymentError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _onExternalWallet);

    WidgetsBinding.instance.addPostFrameCallback((_) => _initiateAndOpen());
  }

  @override
  void dispose() {
    _razorpay.clear();
    super.dispose();
  }

  Future<void> _initiateAndOpen() async {
    setState(() {
      _isProcessing = true;
      _errorMessage = null;
    });

    try {
      final data = await context.read<OrderProvider>().initiatePayment(widget.order.id);
      _gatewayOrderId = data['gateway_order_id'] as String;
      final user = context.read<AuthProvider>().currentUser;

      _razorpay.open({
        'key': data['key'],
        'amount': data['amount'], // already in paise - backend does this conversion, not this screen
        'currency': data['currency'],
        'order_id': _gatewayOrderId,
        'name': AppConstants.appName,
        'description': 'Order ${widget.order.displayId}',
        'prefill': {
          if (user != null) 'contact': user.mobile,
          if (user?.email != null) 'email': user!.email,
        },
      });
    } on ApiException catch (e) {
      setState(() {
        _isProcessing = false;
        _errorMessage = e.message;
      });
    }
  }

  Future<void> _onPaymentSuccess(PaymentSuccessResponse response) async {
    try {
      final order = await context.read<OrderProvider>().verifyPayment(
            razorpayOrderId: response.orderId ?? _gatewayOrderId ?? '',
            razorpayPaymentId: response.paymentId ?? '',
            razorpaySignature: response.signature ?? '',
          );

      if (!mounted) return;
      Navigator.of(context).pushAndRemoveUntil(
        MaterialPageRoute(builder: (_) => OrderConfirmationScreen(order: order)),
        (route) => false,
      );
    } on ApiException catch (e) {
      if (!mounted) return;
      // Payment succeeded at Razorpay but our signature check failed or
      // the request errored - genuinely ambiguous state. The webhook
      // (server-to-server, not dependent on this screen at all) is the
      // real source of truth and will reconcile this independently, but
      // the customer needs an honest message, not a false "failed".
      setState(() {
        _isProcessing = false;
        _errorMessage = 'Payment received but confirmation failed: ${e.message}. '
            'Check My Orders in a moment - it may still confirm automatically.';
      });
    }
  }

  void _onPaymentError(PaymentFailureResponse response) {
    if (!mounted) return;
    setState(() {
      _isProcessing = false;
      _errorMessage = response.message ?? 'Payment was cancelled or failed.';
    });
  }

  void _onExternalWallet(ExternalWalletResponse response) {
    if (!mounted) return;
    setState(() {
      _isProcessing = false;
      _errorMessage = 'Selected wallet: ${response.walletName ?? "unknown"} - not handled separately, treated as unresolved.';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Payment'), automaticallyImplyLeading: false),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              if (_isProcessing) ...[
                const CircularProgressIndicator(),
                const SizedBox(height: 20),
                const Text('Opening secure payment...'),
              ] else if (_errorMessage != null) ...[
                Icon(Icons.error_outline_rounded, size: 40, color: AppColors.error),
                const SizedBox(height: 16),
                Text(_errorMessage!, textAlign: TextAlign.center, style: TextStyle(color: AppColors.textSecondary)),
                const SizedBox(height: 20),
                ElevatedButton(onPressed: _initiateAndOpen, child: const Text('Try again')),
                const SizedBox(height: 8),
                TextButton(
                  onPressed: () => Navigator.of(context).pushAndRemoveUntil(
                    MaterialPageRoute(builder: (_) => const MainShell()),
                    (route) => false,
                  ),
                  child: const Text('Back to home'),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
